version: '3.9'
services:
  db:
    image: postgres
    volumes:
        #  ./tmp/db: -> postgres_volumeへ変更
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    environment: 
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    volumes:
      - .:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
      - selenium_chrome

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
# NEW!! volumeを指定
volumes:
  postgres_volume: